server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: partner

  datasource:
    url: "jdbc:mysql://localhost:3307/partner?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  session:
    timeout: 86400  # session失效时间，单位秒，1天

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER  # 配置路径匹配策略-- 接口文档(Swagger or Knife4j)

mybatis-plus:
  global-config:
    db-config:
      # 表名前缀
      #      table-prefix: tb_
      # id , auto=自增
      id-type: auto
      # 逻辑删除
      logic-delete-field: isDelete    # 逻辑删除字段
      logic-delete-value: 1          # 逻辑已删除值（默认值 1）
      logic-not-delete-value: 0      # 逻辑未删除值（默认值 0）
  configuration:
    # 是否开启骆驼峰 ture=是 false=否
    map-underscore-to-camel-case: false
    # 打开sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # xml 位置
  mapper-locations: classpath*:/mapper/**/*.xml